### ISSUE TITLE
加个功能不要空白

### ISSUE THREAD

**Issue by kkusanagi** [zhujun24/chinese-to-pinyin#10]
现在的功能是
“abc 你好吗 123” =》“abc ni hao ma 123”

能否加个功能不需要空白，就像以下：
“abc 你好吗 123” =》“abc nihaoma 123”

因为在找寻华文时，使用者往往不会自行添加空白。

**Comment by zhujun24** [comment]
已在 v1.3.0 中添加 `removeSpace` 选项，详情参考 README。

**Comment by kkusanagi** [comment]
Error: Unable to resolve module `./dist`
v1.3.0

咦，跟前一个版本相差好大。

**Comment by zhujun24** [comment]
误操作没有提交dist，试下v1.3.1 :)
