### ISSUE TITLE
vue打包错误

### ISSUE THREAD

**Issue by DreamHight** [zhujun24/chinese-to-pinyin#13]
在vue脚手架里这样引入 const pinyin = require('chinese-to-pinyin') ，build的时候出现错误：ERROR in static/js/35.ea5b8b609e60747caaef.js from UglifyJs
Invalid assignment [./node_modules/_chinese-to-pinyin@1.3.1@chinese-to-pinyin/dist/index.js:1,575795][static/js/35.ea5b8b609e60747caaef.js:749,575796]

**Comment by zhujun24** [comment]
先自行搜索一下 `UglifyJs Invalid assignment` 相关的问题吧
