### ISSUE TITLE
Some wrong pinyin transformations

### ISSUE THREAD

**Issue by Connum** [zhujun24/chinese-to-pinyin#3]
你好，

some words in this example sentence are not transformed correctly (regarding to my source, ChinesePod, but I'm actually a beginner in Mandarin):

很特别的日子。你好好想想。
excpected:
hěn tè bié **de** rì zi。nǐ hǎo **hāo** xiǎng **xiang**。
actual result:
hěn tè bié **dē** rì zi。nǐ hǎo **hǎo** xiǎng **xiǎng**。

If a 3rd-tone-word is repeated, shouldn't the second tone be neutral or 1st?

**Comment by zhujun24** [comment]
Hi
I have some confuse about that.
Is all of the repeated 3rd-tone-word should be neutral or 1st ?
Is there a good way to distinguish which repeated 3rd-tone-word should be neutral or 1st or not ?
If you not sure, I would like to add optional config (eg: 3rd-tone-word-repeated-to-1st) to translate it to neutral or 1st.

**Comment by shilik** [comment]
Hi, zhujun24,
As for the 3rd-tone-word should be neutral or not,here is a link for your reference.
http://blog.udn.com/jangjnan/4332597

**Comment by zhujun24** [comment]
@shilik 
According to this blog, we should Identified all of the words and expressions type, which words and expressions is adjective or adverb and any other type, its difficult for this npm package.

**Comment by shilik** [comment]
@zhujun24 
Yes, you are right. There are always some exceptions in terms of natural language.
To solve the problem, I guess that preprocess of segmentation as well as extraction of POS of each word is required, which may not be very cost-effective.
Anyway, thank you for the great plugin, I have managed to finish a project with it like this.https://www.youtube.com/watch?v=k6IvTKZXR-4

**Comment by shilik** [comment]
@zhujun24 
Yes, you are right. There are always some exceptions in terms of natural language.
To solve the problem, I guess that preprocess of segmentation as well as extraction of POS of each word is required, which may not be very cost-effective.
Anyway, thank you for the great plugin, I have managed to finish a project with it like this.https://www.youtube.com/watch?v=k6IvTKZXR-4

**Comment by RichieChoo** [comment]
normal cn translate wrong,
"决策流历史详情“
result:
决 cè liú历史 xiáng qíng

**Comment by zhujun24** [comment]
@RichieChoo 已在1.0.3版本修复该问题，没有重置正则表达式的lastIndex导致的问题
